// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGChordOptions.h"
#include "ChordOptions.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGChordOptions;

namespace djinni_generated {

struct ChordOptions
{
    using CppType = ::SG::ChordOptions;
    using ObjcType = SGChordOptions*;

    using Boxed = ChordOptions;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
