// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGChordOptions.h"


@implementation SGChordOptions

- (nonnull instancetype)initWithShowChord:(BOOL)showChord
                                chordName:(nonnull NSString *)chordName
                       chordRootNoteValue:(int32_t)chordRootNoteValue
                           displayItemsAs:(SGDisplayItemAs)displayItemsAs
{
    if (self = [super init]) {
        _showChord = showChord;
        _chordName = [chordName copy];
        _chordRootNoteValue = chordRootNoteValue;
        _displayItemsAs = displayItemsAs;
    }
    return self;
}

+ (nonnull instancetype)ChordOptionsWithShowChord:(BOOL)showChord
                                        chordName:(nonnull NSString *)chordName
                               chordRootNoteValue:(int32_t)chordRootNoteValue
                                   displayItemsAs:(SGDisplayItemAs)displayItemsAs
{
    return [[self alloc] initWithShowChord:showChord
                                 chordName:chordName
                        chordRootNoteValue:chordRootNoteValue
                            displayItemsAs:displayItemsAs];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p showChord:%@ chordName:%@ chordRootNoteValue:%@ displayItemsAs:%@>", self.class, (void *)self, @(self.showChord), self.chordName, @(self.chordRootNoteValue), @(self.displayItemsAs)];
}

@end
