// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGDisplayItemAs.h"
#import <Foundation/Foundation.h>

@interface SGChordOptions : NSObject
- (nonnull instancetype)initWithShowChord:(BOOL)showChord
                                chordName:(nonnull NSString *)chordName
                       chordRootNoteValue:(int32_t)chordRootNoteValue
                           displayItemsAs:(SGDisplayItemAs)displayItemsAs;
+ (nonnull instancetype)ChordOptionsWithShowChord:(BOOL)showChord
                                        chordName:(nonnull NSString *)chordName
                               chordRootNoteValue:(int32_t)chordRootNoteValue
                                   displayItemsAs:(SGDisplayItemAs)displayItemsAs;

@property (nonatomic, readonly) BOOL showChord;

@property (nonatomic, readonly, nonnull) NSString * chordName;

@property (nonatomic, readonly) int32_t chordRootNoteValue;

@property (nonatomic, readonly) SGDisplayItemAs displayItemsAs;

@end
