// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGChordOptions+Private.h"
#import "DJIMarshal+Private.h"
#import "SGDisplayItemAs+Private.h"
#include <cassert>

namespace djinni_generated {

auto ChordOptions::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Bool::toCpp(obj.showChord),
            ::djinni::String::toCpp(obj.chordName),
            ::djinni::I32::toCpp(obj.chordRootNoteValue),
            ::djinni::Enum<::SG::DisplayItemAs, SGDisplayItemAs>::toCpp(obj.displayItemsAs)};
}

auto ChordOptions::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SGChordOptions alloc] initWithShowChord:(::djinni::Bool::fromCpp(cpp.showChord))
                                           chordName:(::djinni::String::fromCpp(cpp.chordName))
                                  chordRootNoteValue:(::djinni::I32::fromCpp(cpp.chordRootNoteValue))
                                      displayItemsAs:(::djinni::Enum<::SG::DisplayItemAs, SGDisplayItemAs>::fromCpp(cpp.displayItemsAs))];
}

}  // namespace djinni_generated
