// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGGuitarOptions+Private.h"
#import "DJIMarshal+Private.h"
#import "SGAccidentalDisplayType+Private.h"
#include <cassert>

namespace djinni_generated {

auto GuitarOptions::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.guitarType),
            ::djinni::String::toCpp(obj.guitarName),
            ::djinni::Bool::toCpp(obj.showAllNotes),
            ::djinni::Enum<::SG::AccidentalDisplayType, SGAccidentalDisplayType>::toCpp(obj.showNotesAs)};
}

auto GuitarOptions::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SGGuitarOptions alloc] initWithGuitarType:(::djinni::String::fromCpp(cpp.guitarType))
                                            guitarName:(::djinni::String::fromCpp(cpp.guitarName))
                                          showAllNotes:(::djinni::Bool::fromCpp(cpp.showAllNotes))
                                           showNotesAs:(::djinni::Enum<::SG::AccidentalDisplayType, SGAccidentalDisplayType>::fromCpp(cpp.showNotesAs))];
}

}  // namespace djinni_generated
