// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGGuitarOptions.h"
#include "GuitarOptions.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGGuitarOptions;

namespace djinni_generated {

struct GuitarOptions
{
    using CppType = ::SG::GuitarOptions;
    using ObjcType = SGGuitarOptions*;

    using Boxed = GuitarOptions;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
