// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGGuitarOptions.h"


@implementation SGGuitarOptions

- (nonnull instancetype)initWithGuitarType:(nonnull NSString *)guitarType
                                guitarName:(nonnull NSString *)guitarName
                              showAllNotes:(BOOL)showAllNotes
                               showNotesAs:(SGAccidentalDisplayType)showNotesAs
{
    if (self = [super init]) {
        _guitarType = [guitarType copy];
        _guitarName = [guitarName copy];
        _showAllNotes = showAllNotes;
        _showNotesAs = showNotesAs;
    }
    return self;
}

+ (nonnull instancetype)GuitarOptionsWithGuitarType:(nonnull NSString *)guitarType
                                         guitarName:(nonnull NSString *)guitarName
                                       showAllNotes:(BOOL)showAllNotes
                                        showNotesAs:(SGAccidentalDisplayType)showNotesAs
{
    return [[self alloc] initWithGuitarType:guitarType
                                 guitarName:guitarName
                               showAllNotes:showAllNotes
                                showNotesAs:showNotesAs];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p guitarType:%@ guitarName:%@ showAllNotes:%@ showNotesAs:%@>", self.class, (void *)self, self.guitarType, self.guitarName, @(self.showAllNotes), @(self.showNotesAs)];
}

@end
