// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGAccidentalDisplayType.h"
#import <Foundation/Foundation.h>

@interface SGGuitarOptions : NSObject
- (nonnull instancetype)initWithGuitarType:(nonnull NSString *)guitarType
                                guitarName:(nonnull NSString *)guitarName
                              showAllNotes:(BOOL)showAllNotes
                               showNotesAs:(SGAccidentalDisplayType)showNotesAs;
+ (nonnull instancetype)GuitarOptionsWithGuitarType:(nonnull NSString *)guitarType
                                         guitarName:(nonnull NSString *)guitarName
                                       showAllNotes:(BOOL)showAllNotes
                                        showNotesAs:(SGAccidentalDisplayType)showNotesAs;

@property (nonatomic, readonly, nonnull) NSString * guitarType;

@property (nonatomic, readonly, nonnull) NSString * guitarName;

@property (nonatomic, readonly) BOOL showAllNotes;

@property (nonatomic, readonly) SGAccidentalDisplayType showNotesAs;

@end
