// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGScaleOptions.h"


@implementation SGScaleOptions

- (nonnull instancetype)initWithShowScale:(BOOL)showScale
                                scaleName:(nonnull NSString *)scaleName
                       scaleRootNoteValue:(int32_t)scaleRootNoteValue
                           displayItemsAs:(SGDisplayItemAs)displayItemsAs
{
    if (self = [super init]) {
        _showScale = showScale;
        _scaleName = [scaleName copy];
        _scaleRootNoteValue = scaleRootNoteValue;
        _displayItemsAs = displayItemsAs;
    }
    return self;
}

+ (nonnull instancetype)ScaleOptionsWithShowScale:(BOOL)showScale
                                        scaleName:(nonnull NSString *)scaleName
                               scaleRootNoteValue:(int32_t)scaleRootNoteValue
                                   displayItemsAs:(SGDisplayItemAs)displayItemsAs
{
    return [[self alloc] initWithShowScale:showScale
                                 scaleName:scaleName
                        scaleRootNoteValue:scaleRootNoteValue
                            displayItemsAs:displayItemsAs];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p showScale:%@ scaleName:%@ scaleRootNoteValue:%@ displayItemsAs:%@>", self.class, (void *)self, @(self.showScale), self.scaleName, @(self.scaleRootNoteValue), @(self.displayItemsAs)];
}

@end
