// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGDisplayItemAs.h"
#import <Foundation/Foundation.h>

@interface SGScaleOptions : NSObject
- (nonnull instancetype)initWithShowScale:(BOOL)showScale
                                scaleName:(nonnull NSString *)scaleName
                       scaleRootNoteValue:(int32_t)scaleRootNoteValue
                           displayItemsAs:(SGDisplayItemAs)displayItemsAs;
+ (nonnull instancetype)ScaleOptionsWithShowScale:(BOOL)showScale
                                        scaleName:(nonnull NSString *)scaleName
                               scaleRootNoteValue:(int32_t)scaleRootNoteValue
                                   displayItemsAs:(SGDisplayItemAs)displayItemsAs;

@property (nonatomic, readonly) BOOL showScale;

@property (nonatomic, readonly, nonnull) NSString * scaleName;

@property (nonatomic, readonly) int32_t scaleRootNoteValue;

@property (nonatomic, readonly) SGDisplayItemAs displayItemsAs;

@end
