// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGScaleOptions.h"
#include "ScaleOptions.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGScaleOptions;

namespace djinni_generated {

struct ScaleOptions
{
    using CppType = ::SG::ScaleOptions;
    using ObjcType = SGScaleOptions*;

    using Boxed = ScaleOptions;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
