// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGScaleOptions+Private.h"
#import "DJIMarshal+Private.h"
#import "SGDisplayItemAs+Private.h"
#include <cassert>

namespace djinni_generated {

auto ScaleOptions::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Bool::toCpp(obj.showScale),
            ::djinni::String::toCpp(obj.scaleName),
            ::djinni::I32::toCpp(obj.scaleRootNoteValue),
            ::djinni::Enum<::SG::DisplayItemAs, SGDisplayItemAs>::toCpp(obj.displayItemsAs)};
}

auto ScaleOptions::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SGScaleOptions alloc] initWithShowScale:(::djinni::Bool::fromCpp(cpp.showScale))
                                           scaleName:(::djinni::String::fromCpp(cpp.scaleName))
                                  scaleRootNoteValue:(::djinni::I32::fromCpp(cpp.scaleRootNoteValue))
                                      displayItemsAs:(::djinni::Enum<::SG::DisplayItemAs, SGDisplayItemAs>::fromCpp(cpp.displayItemsAs))];
}

}  // namespace djinni_generated
