// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#include "SGuitar.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SGSGuitar;

namespace djinni_generated {

class SGuitar
{
public:
    using CppType = std::shared_ptr<::SG::SGuitar>;
    using CppOptType = std::shared_ptr<::SG::SGuitar>;
    using ObjcType = SGSGuitar*;

    using Boxed = SGuitar;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

