// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGSGuitar+Private.h"
#import "SGSGuitar.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#import "SGChordOptions+Private.h"
#import "SGGuitarOptions+Private.h"
#import "SGScaleOptions+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface SGSGuitar ()

- (id)initWithCpp:(const std::shared_ptr<::SG::SGuitar>&)cppRef;

@end

@implementation SGSGuitar {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::SG::SGuitar>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::SG::SGuitar>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

- (nonnull SGGuitarOptions *)getGuitarOptions {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getGuitarOptions();
        return ::djinni_generated::GuitarOptions::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setGuitarOptions:(nonnull SGGuitarOptions *)options {
    try {
        _cppRefHandle.get()->setGuitarOptions(::djinni_generated::GuitarOptions::toCpp(options));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull SGScaleOptions *)getScaleOptions {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getScaleOptions();
        return ::djinni_generated::ScaleOptions::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setScaleOptions:(nonnull SGScaleOptions *)options {
    try {
        _cppRefHandle.get()->setScaleOptions(::djinni_generated::ScaleOptions::toCpp(options));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull SGChordOptions *)getChordOptions {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getChordOptions();
        return ::djinni_generated::ChordOptions::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (void)setChordOptions:(nonnull SGChordOptions *)options {
    try {
        _cppRefHandle.get()->setChordOptions(::djinni_generated::ChordOptions::toCpp(options));
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<NSNumber *> *)getScaleNoteValues {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getScaleNoteValues();
        return ::djinni::List<::djinni::I32>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSArray<NSNumber *> *)getChordNoteValues {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getChordNoteValues();
        return ::djinni::List<::djinni::I32>::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)isNoteValueInScale:(int32_t)noteValue {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->isNoteValueInScale(::djinni::I32::toCpp(noteValue));
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (BOOL)isNoteValueInChord:(int32_t)noteValue {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->isNoteValueInChord(::djinni::I32::toCpp(noteValue));
        return ::djinni::Bool::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto SGuitar::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto SGuitar::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<SGSGuitar>(cpp);
}

}  // namespace djinni_generated

@end
