// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#import "SGChordOptions.h"
#import "SGGuitarOptions.h"
#import "SGScaleOptions.h"
#import <Foundation/Foundation.h>


@interface SGSGuitar : NSObject

- (nonnull SGGuitarOptions *)getGuitarOptions;

- (void)setGuitarOptions:(nonnull SGGuitarOptions *)options;

- (nonnull SGScaleOptions *)getScaleOptions;

- (void)setScaleOptions:(nonnull SGScaleOptions *)options;

- (nonnull SGChordOptions *)getChordOptions;

- (void)setChordOptions:(nonnull SGChordOptions *)options;

- (nonnull NSArray<NSNumber *> *)getScaleNoteValues;

- (nonnull NSArray<NSNumber *> *)getChordNoteValues;

- (BOOL)isNoteValueInScale:(int32_t)noteValue;

- (BOOL)isNoteValueInChord:(int32_t)noteValue;

@end
