// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

package com.steelsidekick.sguitar;

public final class ChordOptions {


    /*package*/ final boolean mShowChord;

    /*package*/ final String mChordName;

    /*package*/ final int mChordRootNoteValue;

    /*package*/ final DisplayItemAs mDisplayItemsAs;

    public ChordOptions(
            boolean showChord,
            String chordName,
            int chordRootNoteValue,
            DisplayItemAs displayItemsAs) {
        this.mShowChord = showChord;
        this.mChordName = chordName;
        this.mChordRootNoteValue = chordRootNoteValue;
        this.mDisplayItemsAs = displayItemsAs;
    }

    public boolean getShowChord() {
        return mShowChord;
    }

    public String getChordName() {
        return mChordName;
    }

    public int getChordRootNoteValue() {
        return mChordRootNoteValue;
    }

    public DisplayItemAs getDisplayItemsAs() {
        return mDisplayItemsAs;
    }

    @Override
    public String toString() {
        return "ChordOptions{" +
                "mShowChord=" + mShowChord +
                "," + "mChordName=" + mChordName +
                "," + "mChordRootNoteValue=" + mChordRootNoteValue +
                "," + "mDisplayItemsAs=" + mDisplayItemsAs +
        "}";
    }

}
