// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

package com.steelsidekick.sguitar;

public final class GuitarOptions {


    /*package*/ final String mGuitarType;

    /*package*/ final String mGuitarName;

    /*package*/ final boolean mShowAllNotes;

    /*package*/ final AccidentalDisplayType mShowNotesAs;

    public GuitarOptions(
            String guitarType,
            String guitarName,
            boolean showAllNotes,
            AccidentalDisplayType showNotesAs) {
        this.mGuitarType = guitarType;
        this.mGuitarName = guitarName;
        this.mShowAllNotes = showAllNotes;
        this.mShowNotesAs = showNotesAs;
    }

    public String getGuitarType() {
        return mGuitarType;
    }

    public String getGuitarName() {
        return mGuitarName;
    }

    public boolean getShowAllNotes() {
        return mShowAllNotes;
    }

    public AccidentalDisplayType getShowNotesAs() {
        return mShowNotesAs;
    }

    @Override
    public String toString() {
        return "GuitarOptions{" +
                "mGuitarType=" + mGuitarType +
                "," + "mGuitarName=" + mGuitarName +
                "," + "mShowAllNotes=" + mShowAllNotes +
                "," + "mShowNotesAs=" + mShowNotesAs +
        "}";
    }

}
