// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

package com.steelsidekick.sguitar;

public final class ScaleOptions {


    /*package*/ final boolean mShowScale;

    /*package*/ final String mScaleName;

    /*package*/ final int mScaleRootNoteValue;

    /*package*/ final DisplayItemAs mDisplayItemsAs;

    public ScaleOptions(
            boolean showScale,
            String scaleName,
            int scaleRootNoteValue,
            DisplayItemAs displayItemsAs) {
        this.mShowScale = showScale;
        this.mScaleName = scaleName;
        this.mScaleRootNoteValue = scaleRootNoteValue;
        this.mDisplayItemsAs = displayItemsAs;
    }

    public boolean getShowScale() {
        return mShowScale;
    }

    public String getScaleName() {
        return mScaleName;
    }

    public int getScaleRootNoteValue() {
        return mScaleRootNoteValue;
    }

    public DisplayItemAs getDisplayItemsAs() {
        return mDisplayItemsAs;
    }

    @Override
    public String toString() {
        return "ScaleOptions{" +
                "mShowScale=" + mShowScale +
                "," + "mScaleName=" + mScaleName +
                "," + "mScaleRootNoteValue=" + mScaleRootNoteValue +
                "," + "mDisplayItemsAs=" + mDisplayItemsAs +
        "}";
    }

}
