// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

package com.steelsidekick.sguitar;

import java.util.ArrayList;
import java.util.concurrent.atomic.AtomicBoolean;

public abstract class SGuitar {
    public abstract GuitarOptions getGuitarOptions();

    public abstract void setGuitarOptions(GuitarOptions options);

    public abstract ScaleOptions getScaleOptions();

    public abstract void setScaleOptions(ScaleOptions options);

    public abstract ChordOptions getChordOptions();

    public abstract void setChordOptions(ChordOptions options);

    public abstract ArrayList<Integer> getScaleNoteValues();

    public abstract ArrayList<Integer> getChordNoteValues();

    public abstract boolean isNoteValueInScale(int noteValue);

    public abstract boolean isNoteValueInChord(int noteValue);

    private static final class CppProxy extends SGuitar
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public GuitarOptions getGuitarOptions()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getGuitarOptions(this.nativeRef);
        }
        private native GuitarOptions native_getGuitarOptions(long _nativeRef);

        @Override
        public void setGuitarOptions(GuitarOptions options)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setGuitarOptions(this.nativeRef, options);
        }
        private native void native_setGuitarOptions(long _nativeRef, GuitarOptions options);

        @Override
        public ScaleOptions getScaleOptions()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getScaleOptions(this.nativeRef);
        }
        private native ScaleOptions native_getScaleOptions(long _nativeRef);

        @Override
        public void setScaleOptions(ScaleOptions options)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setScaleOptions(this.nativeRef, options);
        }
        private native void native_setScaleOptions(long _nativeRef, ScaleOptions options);

        @Override
        public ChordOptions getChordOptions()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getChordOptions(this.nativeRef);
        }
        private native ChordOptions native_getChordOptions(long _nativeRef);

        @Override
        public void setChordOptions(ChordOptions options)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_setChordOptions(this.nativeRef, options);
        }
        private native void native_setChordOptions(long _nativeRef, ChordOptions options);

        @Override
        public ArrayList<Integer> getScaleNoteValues()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getScaleNoteValues(this.nativeRef);
        }
        private native ArrayList<Integer> native_getScaleNoteValues(long _nativeRef);

        @Override
        public ArrayList<Integer> getChordNoteValues()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_getChordNoteValues(this.nativeRef);
        }
        private native ArrayList<Integer> native_getChordNoteValues(long _nativeRef);

        @Override
        public boolean isNoteValueInScale(int noteValue)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_isNoteValueInScale(this.nativeRef, noteValue);
        }
        private native boolean native_isNoteValueInScale(long _nativeRef, int noteValue);

        @Override
        public boolean isNoteValueInChord(int noteValue)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_isNoteValueInChord(this.nativeRef, noteValue);
        }
        private native boolean native_isNoteValueInChord(long _nativeRef, int noteValue);
    }
}
