// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#include "NativeChordOptions.hpp"  // my header
#include "Marshal.hpp"
#include "NativeDisplayItemAs.hpp"

namespace djinni_generated {

NativeChordOptions::NativeChordOptions() = default;

NativeChordOptions::~NativeChordOptions() = default;

auto NativeChordOptions::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeChordOptions>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.showChord)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.chordName)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.chordRootNoteValue)),
                                                           ::djinni::get(::djinni_generated::NativeDisplayItemAs::fromCpp(jniEnv, c.displayItemsAs)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeChordOptions::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeChordOptions>::get();
    return {::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mShowChord)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mChordName)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mChordRootNoteValue)),
            ::djinni_generated::NativeDisplayItemAs::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mDisplayItemsAs))};
}

}  // namespace djinni_generated
