// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include "ScaleOptions.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeScaleOptions final {
public:
    using CppType = ::SG::ScaleOptions;
    using JniType = jobject;

    using Boxed = NativeScaleOptions;

    ~NativeScaleOptions();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeScaleOptions();
    friend ::djinni::JniClass<NativeScaleOptions>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/ScaleOptions") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ZLjava/lang/String;ILcom/steelsidekick/sguitar/DisplayItemAs;)V") };
    const jfieldID field_mShowScale { ::djinni::jniGetFieldID(clazz.get(), "mShowScale", "Z") };
    const jfieldID field_mScaleName { ::djinni::jniGetFieldID(clazz.get(), "mScaleName", "Ljava/lang/String;") };
    const jfieldID field_mScaleRootNoteValue { ::djinni::jniGetFieldID(clazz.get(), "mScaleRootNoteValue", "I") };
    const jfieldID field_mDisplayItemsAs { ::djinni::jniGetFieldID(clazz.get(), "mDisplayItemsAs", "Lcom/steelsidekick/sguitar/DisplayItemAs;") };
};

}  // namespace djinni_generated
