// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include "AccidentalDisplayType.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeAccidentalDisplayType final : ::djinni::JniEnum {
public:
    using CppType = ::SG::AccidentalDisplayType;
    using JniType = jobject;

    using Boxed = NativeAccidentalDisplayType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeAccidentalDisplayType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeAccidentalDisplayType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeAccidentalDisplayType() : JniEnum("com/steelsidekick/sguitar/AccidentalDisplayType") {}
    friend ::djinni::JniClass<NativeAccidentalDisplayType>;
};

}  // namespace djinni_generated
