// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include "GuitarOptions.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeGuitarOptions final {
public:
    using CppType = ::SG::GuitarOptions;
    using JniType = jobject;

    using Boxed = NativeGuitarOptions;

    ~NativeGuitarOptions();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeGuitarOptions();
    friend ::djinni::JniClass<NativeGuitarOptions>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/GuitarOptions") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;ZLcom/steelsidekick/sguitar/AccidentalDisplayType;)V") };
    const jfieldID field_mGuitarType { ::djinni::jniGetFieldID(clazz.get(), "mGuitarType", "Ljava/lang/String;") };
    const jfieldID field_mGuitarName { ::djinni::jniGetFieldID(clazz.get(), "mGuitarName", "Ljava/lang/String;") };
    const jfieldID field_mShowAllNotes { ::djinni::jniGetFieldID(clazz.get(), "mShowAllNotes", "Z") };
    const jfieldID field_mShowNotesAs { ::djinni::jniGetFieldID(clazz.get(), "mShowNotesAs", "Lcom/steelsidekick/sguitar/AccidentalDisplayType;") };
};

}  // namespace djinni_generated
