// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#include "NativeScaleOptions.hpp"  // my header
#include "Marshal.hpp"
#include "NativeDisplayItemAs.hpp"

namespace djinni_generated {

NativeScaleOptions::NativeScaleOptions() = default;

NativeScaleOptions::~NativeScaleOptions() = default;

auto NativeScaleOptions::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeScaleOptions>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.showScale)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.scaleName)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.scaleRootNoteValue)),
                                                           ::djinni::get(::djinni_generated::NativeDisplayItemAs::fromCpp(jniEnv, c.displayItemsAs)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeScaleOptions::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeScaleOptions>::get();
    return {::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mShowScale)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mScaleName)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mScaleRootNoteValue)),
            ::djinni_generated::NativeDisplayItemAs::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mDisplayItemsAs))};
}

}  // namespace djinni_generated
