// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include "SGuitar.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeSGuitar final : ::djinni::JniInterface<::SG::SGuitar, NativeSGuitar> {
public:
    using CppType = std::shared_ptr<::SG::SGuitar>;
    using CppOptType = std::shared_ptr<::SG::SGuitar>;
    using JniType = jobject;

    using Boxed = NativeSGuitar;

    ~NativeSGuitar();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeSGuitar>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeSGuitar>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeSGuitar();
    friend ::djinni::JniClass<NativeSGuitar>;
    friend ::djinni::JniInterface<::SG::SGuitar, NativeSGuitar>;

};

}  // namespace djinni_generated
