// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#include "NativeSGuitar.hpp"  // my header
#include "Marshal.hpp"
#include "NativeChordOptions.hpp"
#include "NativeGuitarOptions.hpp"
#include "NativeScaleOptions.hpp"

namespace djinni_generated {

NativeSGuitar::NativeSGuitar() : ::djinni::JniInterface<::SG::SGuitar, NativeSGuitar>("com/steelsidekick/sguitar/SGuitar$CppProxy") {}

NativeSGuitar::~NativeSGuitar() = default;


CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_SGuitar_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::SG::SGuitar>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_SGuitar_00024CppProxy_native_1getGuitarOptions(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::SG::SGuitar>(nativeRef);
        auto r = ref->getGuitarOptions();
        return ::djinni::release(::djinni_generated::NativeGuitarOptions::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_SGuitar_00024CppProxy_native_1setGuitarOptions(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_options)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::SG::SGuitar>(nativeRef);
        ref->setGuitarOptions(::djinni_generated::NativeGuitarOptions::toCpp(jniEnv, j_options));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_SGuitar_00024CppProxy_native_1getScaleOptions(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::SG::SGuitar>(nativeRef);
        auto r = ref->getScaleOptions();
        return ::djinni::release(::djinni_generated::NativeScaleOptions::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_SGuitar_00024CppProxy_native_1setScaleOptions(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_options)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::SG::SGuitar>(nativeRef);
        ref->setScaleOptions(::djinni_generated::NativeScaleOptions::toCpp(jniEnv, j_options));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_SGuitar_00024CppProxy_native_1getChordOptions(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::SG::SGuitar>(nativeRef);
        auto r = ref->getChordOptions();
        return ::djinni::release(::djinni_generated::NativeChordOptions::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT void JNICALL Java_com_steelsidekick_sguitar_SGuitar_00024CppProxy_native_1setChordOptions(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jobject j_options)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::SG::SGuitar>(nativeRef);
        ref->setChordOptions(::djinni_generated::NativeChordOptions::toCpp(jniEnv, j_options));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_SGuitar_00024CppProxy_native_1getScaleNoteValues(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::SG::SGuitar>(nativeRef);
        auto r = ref->getScaleNoteValues();
        return ::djinni::release(::djinni::List<::djinni::I32>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jobject JNICALL Java_com_steelsidekick_sguitar_SGuitar_00024CppProxy_native_1getChordNoteValues(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::SG::SGuitar>(nativeRef);
        auto r = ref->getChordNoteValues();
        return ::djinni::release(::djinni::List<::djinni::I32>::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_steelsidekick_sguitar_SGuitar_00024CppProxy_native_1isNoteValueInScale(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_noteValue)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::SG::SGuitar>(nativeRef);
        auto r = ref->isNoteValueInScale(::djinni::I32::toCpp(jniEnv, j_noteValue));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jboolean JNICALL Java_com_steelsidekick_sguitar_SGuitar_00024CppProxy_native_1isNoteValueInChord(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef, jint j_noteValue)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::SG::SGuitar>(nativeRef);
        auto r = ref->isNoteValueInChord(::djinni::I32::toCpp(jniEnv, j_noteValue));
        return ::djinni::release(::djinni::Bool::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
