// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include "ChordOptions.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeChordOptions final {
public:
    using CppType = ::SG::ChordOptions;
    using JniType = jobject;

    using Boxed = NativeChordOptions;

    ~NativeChordOptions();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeChordOptions();
    friend ::djinni::JniClass<NativeChordOptions>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/steelsidekick/sguitar/ChordOptions") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ZLjava/lang/String;ILcom/steelsidekick/sguitar/DisplayItemAs;)V") };
    const jfieldID field_mShowChord { ::djinni::jniGetFieldID(clazz.get(), "mShowChord", "Z") };
    const jfieldID field_mChordName { ::djinni::jniGetFieldID(clazz.get(), "mChordName", "Ljava/lang/String;") };
    const jfieldID field_mChordRootNoteValue { ::djinni::jniGetFieldID(clazz.get(), "mChordRootNoteValue", "I") };
    const jfieldID field_mDisplayItemsAs { ::djinni::jniGetFieldID(clazz.get(), "mDisplayItemsAs", "Lcom/steelsidekick/sguitar/DisplayItemAs;") };
};

}  // namespace djinni_generated
