// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#include "NativeGuitarOptions.hpp"  // my header
#include "Marshal.hpp"
#include "NativeAccidentalDisplayType.hpp"

namespace djinni_generated {

NativeGuitarOptions::NativeGuitarOptions() = default;

NativeGuitarOptions::~NativeGuitarOptions() = default;

auto NativeGuitarOptions::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeGuitarOptions>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.guitarType)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.guitarName)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.showAllNotes)),
                                                           ::djinni::get(::djinni_generated::NativeAccidentalDisplayType::fromCpp(jniEnv, c.showNotesAs)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeGuitarOptions::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeGuitarOptions>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mGuitarType)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mGuitarName)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mShowAllNotes)),
            ::djinni_generated::NativeAccidentalDisplayType::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mShowNotesAs))};
}

}  // namespace djinni_generated
