// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include "DisplayItemAs.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDisplayItemAs final : ::djinni::JniEnum {
public:
    using CppType = ::SG::DisplayItemAs;
    using JniType = jobject;

    using Boxed = NativeDisplayItemAs;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeDisplayItemAs>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeDisplayItemAs>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeDisplayItemAs() : JniEnum("com/steelsidekick/sguitar/DisplayItemAs") {}
    friend ::djinni::JniClass<NativeDisplayItemAs>;
};

}  // namespace djinni_generated
