/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.steelsidekick.sguitar;

public enum DISPLAY_ITEM_AS_TYPE {
  DIA_NOTES,
  DIA_INTERVAL;

  public final int swigValue() {
    return swigValue;
  }

  public static DISPLAY_ITEM_AS_TYPE swigToEnum(int swigValue) {
    DISPLAY_ITEM_AS_TYPE[] swigValues = DISPLAY_ITEM_AS_TYPE.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (DISPLAY_ITEM_AS_TYPE swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + DISPLAY_ITEM_AS_TYPE.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private DISPLAY_ITEM_AS_TYPE() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private DISPLAY_ITEM_AS_TYPE(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private DISPLAY_ITEM_AS_TYPE(DISPLAY_ITEM_AS_TYPE swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

