/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.steelsidekick.sguitar;

public class GUITAR_CANVAS_POSITION {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GUITAR_CANVAS_POSITION(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GUITAR_CANVAS_POSITION obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SGJNI.delete_GUITAR_CANVAS_POSITION(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStringNumber(int value) {
    SGJNI.GUITAR_CANVAS_POSITION_stringNumber_set(swigCPtr, this, value);
  }

  public int getStringNumber() {
    return SGJNI.GUITAR_CANVAS_POSITION_stringNumber_get(swigCPtr, this);
  }

  public void setFretNumber(int value) {
    SGJNI.GUITAR_CANVAS_POSITION_fretNumber_set(swigCPtr, this, value);
  }

  public int getFretNumber() {
    return SGJNI.GUITAR_CANVAS_POSITION_fretNumber_get(swigCPtr, this);
  }

  public GUITAR_CANVAS_POSITION() {
    this(SGJNI.new_GUITAR_CANVAS_POSITION(), true);
  }

}
