/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.steelsidekick.sguitar;

public class SGGuitarOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SGGuitarOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SGGuitarOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SGJNI.delete_SGGuitarOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGuitarType(String value) {
    SGJNI.SGGuitarOptions_guitarType_set(swigCPtr, this, value);
  }

  public String getGuitarType() {
    return SGJNI.SGGuitarOptions_guitarType_get(swigCPtr, this);
  }

  public void setGuitarName(String value) {
    SGJNI.SGGuitarOptions_guitarName_set(swigCPtr, this, value);
  }

  public String getGuitarName() {
    return SGJNI.SGGuitarOptions_guitarName_get(swigCPtr, this);
  }

  public void setShowAllNotes(boolean value) {
    SGJNI.SGGuitarOptions_showAllNotes_set(swigCPtr, this, value);
  }

  public boolean getShowAllNotes() {
    return SGJNI.SGGuitarOptions_showAllNotes_get(swigCPtr, this);
  }

  public void setShowNotesAs(ACCIDENTAL_DISPLAY_TYPE value) {
    SGJNI.SGGuitarOptions_showNotesAs_set(swigCPtr, this, value.swigValue());
  }

  public ACCIDENTAL_DISPLAY_TYPE getShowNotesAs() {
    return ACCIDENTAL_DISPLAY_TYPE.swigToEnum(SGJNI.SGGuitarOptions_showNotesAs_get(swigCPtr, this));
  }

  public SGGuitarOptions() {
    this(SGJNI.new_SGGuitarOptions(), true);
  }

}
