/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.steelsidekick.sguitar;

public class SGJNI {
  public final static native void GUITAR_CANVAS_POSITION_stringNumber_set(long jarg1, GUITAR_CANVAS_POSITION jarg1_, int jarg2);
  public final static native int GUITAR_CANVAS_POSITION_stringNumber_get(long jarg1, GUITAR_CANVAS_POSITION jarg1_);
  public final static native void GUITAR_CANVAS_POSITION_fretNumber_set(long jarg1, GUITAR_CANVAS_POSITION jarg1_, int jarg2);
  public final static native int GUITAR_CANVAS_POSITION_fretNumber_get(long jarg1, GUITAR_CANVAS_POSITION jarg1_);
  public final static native long new_GUITAR_CANVAS_POSITION();
  public final static native void delete_GUITAR_CANVAS_POSITION(long jarg1);
  public final static native void SGGuitarOptions_guitarType_set(long jarg1, SGGuitarOptions jarg1_, String jarg2);
  public final static native String SGGuitarOptions_guitarType_get(long jarg1, SGGuitarOptions jarg1_);
  public final static native void SGGuitarOptions_guitarName_set(long jarg1, SGGuitarOptions jarg1_, String jarg2);
  public final static native String SGGuitarOptions_guitarName_get(long jarg1, SGGuitarOptions jarg1_);
  public final static native void SGGuitarOptions_showAllNotes_set(long jarg1, SGGuitarOptions jarg1_, boolean jarg2);
  public final static native boolean SGGuitarOptions_showAllNotes_get(long jarg1, SGGuitarOptions jarg1_);
  public final static native void SGGuitarOptions_showNotesAs_set(long jarg1, SGGuitarOptions jarg1_, int jarg2);
  public final static native int SGGuitarOptions_showNotesAs_get(long jarg1, SGGuitarOptions jarg1_);
  public final static native long new_SGGuitarOptions();
  public final static native void delete_SGGuitarOptions(long jarg1);
  public final static native void SGScaleOptions_showScale_set(long jarg1, SGScaleOptions jarg1_, boolean jarg2);
  public final static native boolean SGScaleOptions_showScale_get(long jarg1, SGScaleOptions jarg1_);
  public final static native void SGScaleOptions_scaleName_set(long jarg1, SGScaleOptions jarg1_, String jarg2);
  public final static native String SGScaleOptions_scaleName_get(long jarg1, SGScaleOptions jarg1_);
  public final static native void SGScaleOptions_scaleRootNoteValue_set(long jarg1, SGScaleOptions jarg1_, int jarg2);
  public final static native int SGScaleOptions_scaleRootNoteValue_get(long jarg1, SGScaleOptions jarg1_);
  public final static native void SGScaleOptions_displayItemsAs_set(long jarg1, SGScaleOptions jarg1_, int jarg2);
  public final static native int SGScaleOptions_displayItemsAs_get(long jarg1, SGScaleOptions jarg1_);
  public final static native long new_SGScaleOptions();
  public final static native void delete_SGScaleOptions(long jarg1);
  public final static native void SGChordOptions_showChord_set(long jarg1, SGChordOptions jarg1_, boolean jarg2);
  public final static native boolean SGChordOptions_showChord_get(long jarg1, SGChordOptions jarg1_);
  public final static native void SGChordOptions_chordName_set(long jarg1, SGChordOptions jarg1_, String jarg2);
  public final static native String SGChordOptions_chordName_get(long jarg1, SGChordOptions jarg1_);
  public final static native void SGChordOptions_chordRootNoteValue_set(long jarg1, SGChordOptions jarg1_, int jarg2);
  public final static native int SGChordOptions_chordRootNoteValue_get(long jarg1, SGChordOptions jarg1_);
  public final static native void SGChordOptions_displayItemsAs_set(long jarg1, SGChordOptions jarg1_, int jarg2);
  public final static native int SGChordOptions_displayItemsAs_get(long jarg1, SGChordOptions jarg1_);
  public final static native long new_SGChordOptions();
  public final static native void delete_SGChordOptions(long jarg1);
  public final static native long SGuitar_sharedInstance();
  public final static native void SGuitar_setSystemAndUserPaths(String jarg1, String jarg2);
  public final static native long SGuitar_getGuitarOptions(long jarg1, SGuitar jarg1_);
  public final static native void SGuitar_setGuitarOptions(long jarg1, SGuitar jarg1_, long jarg2, SGGuitarOptions jarg2_);
  public final static native long SGuitar_getScaleOptions(long jarg1, SGuitar jarg1_);
  public final static native void SGuitar_setScaleOptions(long jarg1, SGuitar jarg1_, long jarg2, SGScaleOptions jarg2_);
  public final static native long SGuitar_getChordOptions(long jarg1, SGuitar jarg1_);
  public final static native void SGuitar_setChordOptions(long jarg1, SGuitar jarg1_, long jarg2, SGChordOptions jarg2_);
  public final static native long SGuitar_getScaleNoteValues(long jarg1, SGuitar jarg1_);
  public final static native long SGuitar_getChordNoteValues(long jarg1, SGuitar jarg1_);
  public final static native boolean SGuitar_isNoteValueInScale(long jarg1, SGuitar jarg1_, int jarg2);
  public final static native boolean SGuitar_isNoteValueInChord(long jarg1, SGuitar jarg1_, int jarg2);
  public final static native int SGuitar_getNumberOfStrings(long jarg1, SGuitar jarg1_);
  public final static native int SGuitar_getNumberOfFrets(long jarg1, SGuitar jarg1_);
  public final static native long SGuitar_getNoteValuesForString(long jarg1, SGuitar jarg1_, int jarg2);
  public final static native void SGuitar_reloadGuitar(long jarg1, SGuitar jarg1_);
  public final static native boolean SGuitar_isAdjustmentEnabled(long jarg1, SGuitar jarg1_, String jarg2);
  public final static native void SGuitar_activateAdjustment(long jarg1, SGuitar jarg1_, String jarg2, boolean jarg3);
  public final static native int SGuitar_midiValue(long jarg1, SGuitar jarg1_, int jarg2, int jarg3);
  public final static native long SGuitar_positionAtCoordinates(long jarg1, SGuitar jarg1_, float jarg2, float jarg3);
  public final static native void SGuitar_setSelectedItem(long jarg1, SGuitar jarg1_, long jarg2, GUITAR_CANVAS_POSITION jarg2_);
  public final static native void SGuitar_init(long jarg1, SGuitar jarg1_, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6, float jarg7);
  public final static native float SGuitar_cacluateNoteWidthHeight(long jarg1, SGuitar jarg1_, float jarg2, float jarg3);
  public final static native void SGuitar_updateCanvasDimensions(long jarg1, SGuitar jarg1_, float jarg2, float jarg3, float jarg4, float jarg5, float jarg6);
  public final static native void SGuitar_draw(long jarg1, SGuitar jarg1_);
  public final static native long SGuitar_getScaleNames(long jarg1, SGuitar jarg1_);
  public final static native long SGuitar_getChordNames(long jarg1, SGuitar jarg1_);
  public final static native long SGuitar_getGuitarTypeNames(long jarg1, SGuitar jarg1_);
  public final static native long SGuitar_getGuitarNames(long jarg1, SGuitar jarg1_, String jarg2);
  public final static native long SGuitar_getCustomGuitarNames(long jarg1, SGuitar jarg1_);
  public final static native boolean SGuitar_removeCustomGuitar(long jarg1, SGuitar jarg1_, String jarg2);
  public final static native String SGuitar_getNoteNameSharpFlat(int jarg1);
  public final static native String SGuitar_getPedalTypeName(int jarg1);
  public final static native String SGuitar_getLeverTypeName(int jarg1);
  public final static native String SGuitar_getDescription(long jarg1, SGuitar jarg1_);
  public final static native long new_StdStringVector__SWIG_0();
  public final static native long new_StdStringVector__SWIG_1(long jarg1);
  public final static native long StdStringVector_size(long jarg1, StdStringVector jarg1_);
  public final static native long StdStringVector_capacity(long jarg1, StdStringVector jarg1_);
  public final static native void StdStringVector_reserve(long jarg1, StdStringVector jarg1_, long jarg2);
  public final static native boolean StdStringVector_isEmpty(long jarg1, StdStringVector jarg1_);
  public final static native void StdStringVector_clear(long jarg1, StdStringVector jarg1_);
  public final static native void StdStringVector_add(long jarg1, StdStringVector jarg1_, String jarg2);
  public final static native String StdStringVector_get(long jarg1, StdStringVector jarg1_, int jarg2);
  public final static native void StdStringVector_set(long jarg1, StdStringVector jarg1_, int jarg2, String jarg3);
  public final static native void delete_StdStringVector(long jarg1);
  public final static native long new_IntVector__SWIG_0();
  public final static native long new_IntVector__SWIG_1(long jarg1);
  public final static native long IntVector_size(long jarg1, IntVector jarg1_);
  public final static native long IntVector_capacity(long jarg1, IntVector jarg1_);
  public final static native void IntVector_reserve(long jarg1, IntVector jarg1_, long jarg2);
  public final static native boolean IntVector_isEmpty(long jarg1, IntVector jarg1_);
  public final static native void IntVector_clear(long jarg1, IntVector jarg1_);
  public final static native void IntVector_add(long jarg1, IntVector jarg1_, int jarg2);
  public final static native int IntVector_get(long jarg1, IntVector jarg1_, int jarg2);
  public final static native void IntVector_set(long jarg1, IntVector jarg1_, int jarg2, int jarg3);
  public final static native void delete_IntVector(long jarg1);
}
