/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.steelsidekick.sguitar;

public class SGScaleOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SGScaleOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SGScaleOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SGJNI.delete_SGScaleOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setShowScale(boolean value) {
    SGJNI.SGScaleOptions_showScale_set(swigCPtr, this, value);
  }

  public boolean getShowScale() {
    return SGJNI.SGScaleOptions_showScale_get(swigCPtr, this);
  }

  public void setScaleName(String value) {
    SGJNI.SGScaleOptions_scaleName_set(swigCPtr, this, value);
  }

  public String getScaleName() {
    return SGJNI.SGScaleOptions_scaleName_get(swigCPtr, this);
  }

  public void setScaleRootNoteValue(int value) {
    SGJNI.SGScaleOptions_scaleRootNoteValue_set(swigCPtr, this, value);
  }

  public int getScaleRootNoteValue() {
    return SGJNI.SGScaleOptions_scaleRootNoteValue_get(swigCPtr, this);
  }

  public void setDisplayItemsAs(DISPLAY_ITEM_AS_TYPE value) {
    SGJNI.SGScaleOptions_displayItemsAs_set(swigCPtr, this, value.swigValue());
  }

  public DISPLAY_ITEM_AS_TYPE getDisplayItemsAs() {
    return DISPLAY_ITEM_AS_TYPE.swigToEnum(SGJNI.SGScaleOptions_displayItemsAs_get(swigCPtr, this));
  }

  public SGScaleOptions() {
    this(SGJNI.new_SGScaleOptions(), true);
  }

}
