/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.steelsidekick.sguitar;

public class StdStringVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StdStringVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StdStringVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        SGJNI.delete_StdStringVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StdStringVector() {
    this(SGJNI.new_StdStringVector__SWIG_0(), true);
  }

  public StdStringVector(long n) {
    this(SGJNI.new_StdStringVector__SWIG_1(n), true);
  }

  public long size() {
    return SGJNI.StdStringVector_size(swigCPtr, this);
  }

  public long capacity() {
    return SGJNI.StdStringVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    SGJNI.StdStringVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return SGJNI.StdStringVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    SGJNI.StdStringVector_clear(swigCPtr, this);
  }

  public void add(String x) {
    SGJNI.StdStringVector_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return SGJNI.StdStringVector_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    SGJNI.StdStringVector_set(swigCPtr, this, i, val);
  }

}
