// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include <functional>

namespace SG {

enum class AccidentalDisplayType : int {
    SHARP,
    FLAT,
};

}  // namespace SG

namespace std {

template <>
struct hash<::SG::AccidentalDisplayType> {
    size_t operator()(::SG::AccidentalDisplayType type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
