// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include "DisplayItemAs.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace SG {

struct ChordOptions final {
    bool showChord;
    std::string chordName;
    int32_t chordRootNoteValue;
    DisplayItemAs displayItemsAs;

    ChordOptions(bool showChord_,
                 std::string chordName_,
                 int32_t chordRootNoteValue_,
                 DisplayItemAs displayItemsAs_)
    : showChord(std::move(showChord_))
    , chordName(std::move(chordName_))
    , chordRootNoteValue(std::move(chordRootNoteValue_))
    , displayItemsAs(std::move(displayItemsAs_))
    {}
};

}  // namespace SG
