// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include <functional>

namespace SG {

enum class DisplayItemAs : int {
    NOTE,
    INTERVAL,
};

}  // namespace SG

namespace std {

template <>
struct hash<::SG::DisplayItemAs> {
    size_t operator()(::SG::DisplayItemAs type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
