// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include "AccidentalDisplayType.hpp"
#include <string>
#include <utility>

namespace SG {

struct GuitarOptions final {
    std::string guitarType;
    std::string guitarName;
    bool showAllNotes;
    AccidentalDisplayType showNotesAs;

    GuitarOptions(std::string guitarType_,
                  std::string guitarName_,
                  bool showAllNotes_,
                  AccidentalDisplayType showNotesAs_)
    : guitarType(std::move(guitarType_))
    , guitarName(std::move(guitarName_))
    , showAllNotes(std::move(showAllNotes_))
    , showNotesAs(std::move(showNotesAs_))
    {}
};

}  // namespace SG
