// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include "DisplayItemAs.hpp"
#include <cstdint>
#include <string>
#include <utility>

namespace SG {

struct ScaleOptions final {
    bool showScale;
    std::string scaleName;
    int32_t scaleRootNoteValue;
    DisplayItemAs displayItemsAs;

    ScaleOptions(bool showScale_,
                 std::string scaleName_,
                 int32_t scaleRootNoteValue_,
                 DisplayItemAs displayItemsAs_)
    : showScale(std::move(showScale_))
    , scaleName(std::move(scaleName_))
    , scaleRootNoteValue(std::move(scaleRootNoteValue_))
    , displayItemsAs(std::move(displayItemsAs_))
    {}
};

}  // namespace SG
