// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sguitar.djinni

#pragma once

#include <cstdint>
#include <vector>

namespace SG {

struct ChordOptions;
struct GuitarOptions;
struct ScaleOptions;

class SGuitar {
public:
    virtual ~SGuitar() {}

    virtual GuitarOptions getGuitarOptions() = 0;

    virtual void setGuitarOptions(const GuitarOptions & options) = 0;

    virtual ScaleOptions getScaleOptions() = 0;

    virtual void setScaleOptions(const ScaleOptions & options) = 0;

    virtual ChordOptions getChordOptions() = 0;

    virtual void setChordOptions(const ChordOptions & options) = 0;

    virtual std::vector<int32_t> getScaleNoteValues() = 0;

    virtual std::vector<int32_t> getChordNoteValues() = 0;

    virtual bool isNoteValueInScale(int32_t noteValue) = 0;

    virtual bool isNoteValueInChord(int32_t noteValue) = 0;
};

}  // namespace SG
